Repository Tourmates/Tourmates-Server, pull requests merged in 2023-05, with the labels that each got.

#2 Feature/#1 join member
  dosc/MEMBER.md
  src/main/java/com/ssafy/tourmates/TourmatesApplication.java
  src/main/java/com/ssafy/tourmates/common/domain/TimeBaseEntity.java
  src/main/java/com/ssafy/tourmates/common/exception/DuplicateException.java
  src/main/java/com/ssafy/tourmates/controller/HomeApiController.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/JoinMemberRequest.java
  src/main/java/com/ssafy/tourmates/member/Active.java
  src/main/java/com/ssafy/tourmates/member/Gender.java
  src/main/java/com/ssafy/tourmates/member/Member.java
  src/main/java/com/ssafy/tourmates/member/repository/MemberRepository.java
  src/main/java/com/ssafy/tourmates/member/service/MemberService.java
  src/main/java/com/ssafy/tourmates/member/service/dto/JoinMemberDto.java
  src/main/java/com/ssafy/tourmates/member/service/impl/MemberServiceImpl.java
  src/test/java/com/ssafy/tourmates/member/service/MemberServiceTest.java
Labels: feature

#6 Feature/#5 forgot account
  dosc/MEMBER.md
  src/main/java/com/ssafy/tourmates/controller/HomeApiController.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/ForgotLoginIdRequest.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/ForgotLoginPwRequest.java
  src/main/java/com/ssafy/tourmates/member/service/MemberQueryService.java
  src/main/java/com/ssafy/tourmates/member/service/MemberService.java
  src/main/java/com/ssafy/tourmates/member/service/impl/MemberQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/member/validator/MemberValidator.java
  src/test/java/com/ssafy/tourmates/member/service/MemberQueryServiceTest.java
  src/test/java/com/ssafy/tourmates/member/validator/MemberValidatorTest.java
Labels: feature

#8 Feature/#7 edit member
  dosc/MEMBER.md
  src/main/java/com/ssafy/tourmates/common/exception/EditException.java
  src/main/java/com/ssafy/tourmates/controller/MemberController.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/EditEmailRequest.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/EditLoginPwRequest.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/EditNicknameRequest.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/EditTelRequest.java
  src/main/java/com/ssafy/tourmates/member/Member.java
  src/main/java/com/ssafy/tourmates/member/service/MemberService.java
  src/main/java/com/ssafy/tourmates/member/service/dto/EditLoginPwDto.java
  src/main/java/com/ssafy/tourmates/member/service/impl/MemberServiceImpl.java
  src/test/java/com/ssafy/tourmates/member/MemberTest.java
  src/test/java/com/ssafy/tourmates/member/service/MemberServiceTest.java
Labels: feature

#10 Feature/#9 withdrawal
  dosc/MEMBER.md
  src/main/java/com/ssafy/tourmates/controller/MemberController.java
  src/main/java/com/ssafy/tourmates/controller/dto/member/request/WithdrawalRequest.java
  src/main/java/com/ssafy/tourmates/member/Member.java
  src/main/java/com/ssafy/tourmates/member/service/MemberService.java
  src/main/java/com/ssafy/tourmates/member/service/impl/MemberServiceImpl.java
  src/test/java/com/ssafy/tourmates/member/MemberTest.java
  src/test/java/com/ssafy/tourmates/member/service/MemberServiceTest.java
Labels: feature

#12 Feature/#11 swagger
  pom.xml
  src/main/java/com/ssafy/tourmates/config/SwaggerConfig.java
  src/main/java/com/ssafy/tourmates/controller/HomeApiController.java
  src/main/java/com/ssafy/tourmates/controller/MemberController.java
  src/main/resources/application.properties
Labels: feature

#14 Feature/#13 search attraction
  src/main/java/com/ssafy/tourmates/attraction/AttractionInfo.java
  src/main/java/com/ssafy/tourmates/attraction/Gugun.java
  src/main/java/com/ssafy/tourmates/attraction/Sido.java
  src/main/java/com/ssafy/tourmates/attraction/repository/AttractionRepository.java
  src/main/java/com/ssafy/tourmates/attraction/repository/AttractionRepositoryCustom.java
  src/main/java/com/ssafy/tourmates/attraction/repository/dto/AttractionSearchCondition.java
  src/main/java/com/ssafy/tourmates/attraction/repository/impl/AttractionRepositoryImpl.java
  src/main/java/com/ssafy/tourmates/controller/dto/attraction/response/AttractionResponse.java
Labels: feature

#16 Feature/#15 register hot place
  dosc/HOTPLACE.md
  src/main/java/com/ssafy/tourmates/attraction/validator/AttractionValidator.java
  src/main/java/com/ssafy/tourmates/common/FileStore.java
  src/main/java/com/ssafy/tourmates/common/domain/ContentType.java
  src/main/java/com/ssafy/tourmates/common/domain/UploadFile.java
  src/main/java/com/ssafy/tourmates/controller/HotPlaceController.java
  src/main/java/com/ssafy/tourmates/controller/dto/hotplace/request/AddHotPlaceRequest.java
  src/main/java/com/ssafy/tourmates/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/HotPlaceRepository.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/HotPlaceRepositoryCustom.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/impl/HotPlaceRepositoryImpl.java
  src/main/java/com/ssafy/tourmates/hotplace/service/HotPlaceService.java
  src/main/java/com/ssafy/tourmates/hotplace/service/dto/AddHotPlaceDto.java
  src/main/java/com/ssafy/tourmates/hotplace/service/impl/HotPlaceServiceImpl.java
  src/test/java/com/ssafy/tourmates/attraction/validator/AttractionValidatorTest.java
  src/test/java/com/ssafy/tourmates/hotplace/service/HotPlaceServiceTest.java
Labels: feature

#18 Feature/#17 search hot place
  dosc/HOTPLACE.md
  src/main/java/com/ssafy/tourmates/controller/HotPlaceController.java
  src/main/java/com/ssafy/tourmates/controller/dto/hotplace/response/DetailHotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/controller/dto/hotplace/response/HotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/hotplace/HotPlaceImage.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/HotPlaceQueryRepository.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/HotPlaceRepository.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/HotPlaceRepositoryCustom.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/dto/HotPlaceSearchCondition.java
  src/main/java/com/ssafy/tourmates/hotplace/repository/impl/HotPlaceRepositoryImpl.java
  src/main/java/com/ssafy/tourmates/hotplace/service/HotPlaceQueryService.java
  src/main/java/com/ssafy/tourmates/hotplace/service/impl/HotPlaceQueryServiceImpl.java
Labels: feature

#23 Feature/#22 remove hotplace
  dosc/HOTPLACE.md
  src/main/java/com/ssafy/tourmates/controller/HotPlaceController.java
  src/main/java/com/ssafy/tourmates/controller/dto/hotplace/request/EditHotPlaceRequest.java
  src/main/java/com/ssafy/tourmates/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/hotplace/service/HotPlaceService.java
  src/main/java/com/ssafy/tourmates/hotplace/service/impl/HotPlaceServiceImpl.java
  src/test/java/com/ssafy/tourmates/hotplace/service/HotPlaceServiceTest.java
  src/test/java/com/ssafy/tourmates/hotplace/validator/HotPlaceValidatorTest.java
Labels: feature

#27 Feature/#26 edit notice
  dosc/NOTICE.md
  src/main/java/com/ssafy/tourmates/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/controller/dto/notice/request/EditNoticeRequest.java
  src/main/java/com/ssafy/tourmates/notice/Notice.java
  src/main/java/com/ssafy/tourmates/notice/service/NoticeService.java
  src/main/java/com/ssafy/tourmates/notice/service/dto/EditNoticeDto.java
  src/main/java/com/ssafy/tourmates/notice/service/impl/NoticeServiceImpl.java
  src/main/java/com/ssafy/tourmates/notice/validator/NoticeValidator.java
  src/test/java/com/ssafy/tourmates/notice/service/NoticeServiceTest.java
  src/test/java/com/ssafy/tourmates/notice/validator/NoticeValidatorTest.java
Labels: feature

#29 Feature/#28 remove notice
  dosc/NOTICE.md
  src/main/java/com/ssafy/tourmates/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/notice/Notice.java
  src/main/java/com/ssafy/tourmates/notice/service/NoticeService.java
  src/main/java/com/ssafy/tourmates/notice/service/impl/NoticeServiceImpl.java
  src/test/java/com/ssafy/tourmates/notice/NoticeTest.java
  src/test/java/com/ssafy/tourmates/notice/service/NoticeServiceTest.java
Labels: feature

#31 Feature/#30 search notices by condition
  dosc/NOTICE.md
  src/main/java/com/ssafy/tourmates/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/controller/dto/notice/response/NoticeResponse.java
  src/main/java/com/ssafy/tourmates/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/notice/repository/dto/NoticeSearchCondition.java
  src/main/java/com/ssafy/tourmates/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/notice/service/impl/NoticeQueryServiceImpl.java
Labels: feature

#33 Feature/#32 search notice
  dosc/NOTICE.md
  src/main/java/com/ssafy/tourmates/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/controller/dto/notice/response/DetailNoticeResponse.java
  src/main/java/com/ssafy/tourmates/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/notice/service/impl/NoticeQueryServiceImpl.java
Labels: feature

#36 Feature/#34 register board
  dosc/BOARD.md
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/impl/AttractionRepositoryImpl.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/Board.java
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardRepository.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardService.java
  src/main/java/com/ssafy/tourmates/client/board/service/dto/AddBoardDto.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/request/AddBoardRequest.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceQueryRepository.java
  src/test/java/com/ssafy/tourmates/client/board/service/BoardServiceTest.java
Labels: feature

#38 Feature/#37 edit board
  dosc/BOARD.md
  src/main/java/com/ssafy/tourmates/client/board/Board.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardService.java
  src/main/java/com/ssafy/tourmates/client/board/service/dto/EditBoardDto.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/board/validator/BoardValidator.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/request/EditBoardRequest.java
  src/test/java/com/ssafy/tourmates/client/board/validator/BoardValidatorTest.java
Labels: feature

#40 Feature/#39 remove board
  dosc/BOARD.md
  src/main/java/com/ssafy/tourmates/client/board/Board.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardService.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardServiceImpl.java
  src/test/java/com/ssafy/tourmates/client/board/BoardTest.java
  src/test/java/com/ssafy/tourmates/client/board/service/BoardServiceTest.java
Labels: feature

#42 Feature/#41 search board by condition
  dosc/BOARD.md
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/repository/dto/BoardSearchCondition.java
  src/main/java/com/ssafy/tourmates/client/board/repository/dto/Sort.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardQueryService.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/response/BoardResponse.java
Labels: feature

#44 Feature/#43 search board
  dosc/BOARD.md
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardQueryService.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/response/DetailBoardResponse.java
Labels: feature

#46 feat: 회원 더미 데이터 구현
  src/main/java/com/ssafy/tourmates/data/InitData.java
Labels: data

#48 Feature/#47 increase hit board
  src/main/java/com/ssafy/tourmates/client/board/Board.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardService.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/test/java/com/ssafy/tourmates/client/board/BoardTest.java
  src/test/java/com/ssafy/tourmates/client/board/service/BoardServiceTest.java
Labels: feature

#49 Feature/#35 register hot place comment
  dosc/HOTPLACECOMMENT.md
  src/main/java/com/ssafy/tourmates/client/controller/HotPlaceController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/hotplace/request/AddHotplaceCommentRequest.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/hotplace/request/EditHotPlaceCommentRequest.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/hotplace/response/DetailHotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/client/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/client/hotplace/HotPlaceComment.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceCommentQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotplaceCommentRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/HotplaceCommentQueryService.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/HotplaceCommentService.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/dto/AddHotPlaceCommentDto.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/dto/EditHotPlaceCommentDto.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotplaceCommentQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotplaceCommentServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/validator/HotPlaceCommentValidator.java
  src/test/java/com/ssafy/tourmates/client/hotplace/service/HotPlaceCommentServiceTest.java
Labels: feature

#57 feat: CORS config 설정
  src/main/java/com/ssafy/tourmates/config/WebConfig.java
Labels: feature

#59 Feature/#58 login
  src/main/java/com/ssafy/tourmates/client/controller/HomeApiController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/member/request/LoginRequest.java
  src/main/java/com/ssafy/tourmates/client/member/service/CustomUserDetailsService.java
  src/main/java/com/ssafy/tourmates/client/member/service/MemberQueryService.java
  src/main/java/com/ssafy/tourmates/client/member/service/impl/MemberQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
  src/main/java/com/ssafy/tourmates/data/InitData.java
Labels: feature

#61 feat: security 설정 추가
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardQueryService.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/response/BoardResponse.java
  src/main/java/com/ssafy/tourmates/common/PageDto.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
Labels: refactor

#63 Refactor/#62 search notice
  src/main/java/com/ssafy/tourmates/admin/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/response/NoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
  src/main/java/com/ssafy/tourmates/data/InitData.java
Labels: refactor

#83 Refactor/#70 search notices
  src/main/java/com/ssafy/tourmates/admin/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/response/DetailNoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/response/NoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeQueryServiceImpl.java
  src/test/resources/application.properties
Labels: refactor

#89 Feature/#84 remove board
  src/main/java/com/ssafy/tourmates/client/board/BoardComment.java
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardCommentService.java
  src/main/java/com/ssafy/tourmates/client/board/service/dto/AddBoardCommentDto.java
  src/main/java/com/ssafy/tourmates/client/board/service/dto/EditBoardCommentDto.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardCommentServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/board/validator/BoardCommentValidator.java
  src/main/java/com/ssafy/tourmates/client/controller/BoardController.java
  src/main/java/com/ssafy/tourmates/client/controller/TripPlanController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/board/response/DetailBoardResponse.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/TripPlan.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/dto/AddTripPlanDto.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/impl/TripPlanServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/validator/TripPlanValidator.java
Labels: feature

#92 Feature/#90 edit notice
  src/main/java/com/ssafy/tourmates/admin/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/response/EditNoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeQueryServiceImpl.java
Labels: feature

#98 Feature/#97 add admin
  src/main/java/com/ssafy/tourmates/admin/admin/Admin.java
  src/main/java/com/ssafy/tourmates/admin/admin/repository/AdminRepository.java
  src/main/java/com/ssafy/tourmates/admin/admin/service/AdminService.java
  src/main/java/com/ssafy/tourmates/admin/admin/service/dto/AddAdminDto.java
  src/main/java/com/ssafy/tourmates/admin/admin/service/impl/AdminServiceImpl.java
  src/test/java/com/ssafy/tourmates/admin/admin/service/AdminServiceTest.java
Labels: feature

#104 Feature/#100 notice admin
  pom.xml
  src/main/java/com/ssafy/tourmates/admin/admin/repository/AdminRepository.java
  src/main/java/com/ssafy/tourmates/admin/admin/validator/AdminValidator.java
  src/main/java/com/ssafy/tourmates/admin/api/NoticeApiController.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/notice/request/EditNoticeRequest.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/notice/response/DetailNoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/notice/response/EditNoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/notice/response/NoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/controller/AdminController.java
  src/main/java/com/ssafy/tourmates/admin/controller/NoticeController.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/form/AddNoticeForm.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/form/EditNoticeForm.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/request/AddNoticeRequest.java
  src/main/java/com/ssafy/tourmates/admin/controller/dto/notice/response/AdminNoticeResponse.java
  src/main/java/com/ssafy/tourmates/admin/notice/Notice.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
  src/main/java/com/ssafy/tourmates/data/InitData.java
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/noticeList.html
Labels: feature

#119 Feature/#118 register question
  src/main/java/com/ssafy/tourmates/client/controller/QuestionController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/question/request/AddQuestionRequest.java
  src/main/java/com/ssafy/tourmates/client/question/Question.java
  src/main/java/com/ssafy/tourmates/client/question/QuestionType.java
  src/main/java/com/ssafy/tourmates/client/question/repository/QuestionRepository.java
  src/main/java/com/ssafy/tourmates/client/question/service/QuestionService.java
  src/main/java/com/ssafy/tourmates/client/question/service/dto/AddQuestionDto.java
  src/main/java/com/ssafy/tourmates/client/question/service/impl/QuestionServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
Labels: feature

#120 Feature/#118 register question
  src/main/java/com/ssafy/tourmates/client/controller/QuestionController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/question/request/AddQuestionRequest.java
  src/main/java/com/ssafy/tourmates/client/question/Question.java
  src/main/java/com/ssafy/tourmates/client/question/service/dto/AddQuestionDto.java
  src/main/java/com/ssafy/tourmates/client/question/service/impl/QuestionServiceImpl.java
Labels: feature

#122 Feature/#121 register answer
  src/main/java/com/ssafy/tourmates/admin/answer/Answer.java
  src/main/java/com/ssafy/tourmates/admin/answer/repository/AnswerRepository.java
  src/main/java/com/ssafy/tourmates/admin/answer/service/AnswerService.java
  src/main/java/com/ssafy/tourmates/admin/answer/service/dto/AddAnswerDto.java
  src/main/java/com/ssafy/tourmates/admin/answer/service/impl/AnswerServiceImpl.java
Labels: feature

#124 Feature/#123 search question
  src/main/java/com/ssafy/tourmates/client/controller/QuestionController.java
  src/main/java/com/ssafy/tourmates/client/controller/dto/question/response/QuestionResponse.java
  src/main/java/com/ssafy/tourmates/client/question/Question.java
  src/main/java/com/ssafy/tourmates/client/question/repository/QuestionQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/question/repository/dto/QuestionSearchCondition.java
  src/main/java/com/ssafy/tourmates/client/question/service/QuestionQueryService.java
  src/main/java/com/ssafy/tourmates/client/question/service/impl/QuestionQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/question/service/impl/QuestionServiceImpl.java
Labels: feature

#129 Refactor/#128 refactor board comment
  src/main/java/com/ssafy/tourmates/client/api/BoardApiController.java
  src/main/java/com/ssafy/tourmates/client/api/BoardCommentApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/board/request/AddBoardCommentRequest.java
  src/main/java/com/ssafy/tourmates/client/board/BoardComment.java
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardCommentQueryRepositoryImpl.java
  src/main/java/com/ssafy/tourmates/client/board/repository/BoardCommentRepository.java
  src/main/java/com/ssafy/tourmates/client/board/service/BoardCommentService.java
  src/main/java/com/ssafy/tourmates/client/board/service/dto/AddBoardCommentDto.java
  src/main/java/com/ssafy/tourmates/client/board/service/impl/BoardCommentServiceImpl.java
Labels: refactor

#132 Refactor/#130 refactor hot place comment
  src/main/java/com/ssafy/tourmates/client/api/HotPlaceApiController.java
  src/main/java/com/ssafy/tourmates/client/api/HotPlaceCommentApiController.java
  src/main/java/com/ssafy/tourmates/client/hotplace/HotPlaceComment.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceCommentQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceCommentRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/HotPlaceCommentService.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceCommentQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceCommentServiceImpl.java
Labels: refactor

#134 Refactor/#133 refactor trip plan comment
  src/main/java/com/ssafy/tourmates/client/api/TripPlanApiController.java
  src/main/java/com/ssafy/tourmates/client/api/TripPlanCommentApiController.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/TripPlanComment.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/TripPlanCommentService.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/impl/TripPlanCommentServiceImpl.java
Labels: refactor

#136 Feature/#135 duplicate join
  src/main/java/com/ssafy/tourmates/client/api/DuplicateApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/member/request/CheckEmailRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/member/request/CheckLoginIdRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/member/request/CheckNicknameRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/member/request/JoinMemberRequest.java
  src/main/java/com/ssafy/tourmates/client/member/repository/MemberQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/member/service/DuplicateCheckService.java
  src/main/java/com/ssafy/tourmates/client/member/service/impl/DuplicateCheckServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
  src/main/java/com/ssafy/tourmates/data/InitData.java
  src/main/resources/static/js/dashboard.js
  src/main/resources/templates/dashboard.html
Labels: feature

#144 Refactor/#140 refactor hot place
  src/main/java/com/ssafy/tourmates/admin/attraction/AttractionInfo.java
  src/main/java/com/ssafy/tourmates/client/api/HotPlaceApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/hotplace/request/AddHotPlaceRequest.java
  src/main/java/com/ssafy/tourmates/client/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
Labels: refactor

#156 Feature/#146 search attraction
  src/main/java/com/ssafy/tourmates/admin/api/AttractionApiController.java
  src/main/java/com/ssafy/tourmates/admin/api/NoticeApiController.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/attraction/response/AttractionResponse.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/attraction/response/AttractionSearchResponse.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/attraction/response/GugunResponse.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/attraction/response/SidoResponse.java
  src/main/java/com/ssafy/tourmates/admin/attraction/AttractionInfo.java
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/AttractionQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/AttractionRepositoryCustom.java
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/dto/AttractionSearchCondition.java
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/impl/AttractionQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/attraction/service/AttractionQueryService.java
  src/main/java/com/ssafy/tourmates/admin/attraction/service/impl/AttractionQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/admin/controller/AttractionController.java
  src/main/java/com/ssafy/tourmates/client/api/HotPlaceApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/hotplace/response/HotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/HotPlaceQueryService.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/common/domain/ContentType.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
Labels: feature

#164 Feature/#159 search attractions
  src/main/java/com/ssafy/tourmates/admin/api/AttractionApiController.java
  src/main/java/com/ssafy/tourmates/admin/api/dto/attraction/response/AttractionTripPlanResponse.java
  src/main/java/com/ssafy/tourmates/admin/attraction/repository/AttractionQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/attraction/service/AttractionQueryService.java
  src/main/java/com/ssafy/tourmates/admin/attraction/service/impl/AttractionQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/api/TripPlanApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripPlan/AddTripPlanRequest.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/TripPlan.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/dto/AddTripPlanDto.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/impl/TripPlanServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
Labels: feature

#167 Feature/#165 search trip plans
  src/main/java/com/ssafy/tourmates/client/api/TripPlanApiController.java
  src/main/java/com/ssafy/tourmates/client/api/TripPlanCommentApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/request/AddDetailPlanRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/request/AddTripPlanCommentRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/request/AddTripPlanRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/request/EditTripPlanCommentReqeust.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/request/EditTripPlanRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/response/DetailPlanDataResponse.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/response/DetailPlanResponse.java
  src/main/java/com/ssafy/tourmates/client/api/dto/tripplan/response/PlanResponse.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/TripPlan.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/repository/TripPlanQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/repository/dto/PlanSearchCondition.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/TripPlanQueryService.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/TripPlanService.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/impl/TripPlanQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/tripPlan/service/impl/TripPlanServiceImpl.java
  src/main/java/com/ssafy/tourmates/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: feature

#177 Refactor/#176 refactor notice
  src/main/java/com/ssafy/tourmates/admin/api/NoticeApiController.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/NoticeQueryRepository.java
  src/main/java/com/ssafy/tourmates/admin/notice/repository/dto/NoticeSearchCondition.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/NoticeQueryService.java
  src/main/java/com/ssafy/tourmates/admin/notice/service/impl/NoticeQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/api/TripPlanApiController.java
Labels: refactor

#188 refactor: 핫플레이스 리팩토링 및 해시태그 구현
  sql/dump.sql
  src/main/java/com/ssafy/tourmates/client/api/BoardApiController.java
  src/main/java/com/ssafy/tourmates/client/api/HotPlaceApiController.java
  src/main/java/com/ssafy/tourmates/client/api/dto/board/response/BoardResponse.java
  src/main/java/com/ssafy/tourmates/client/api/dto/hotplace/request/AddHotPlaceRequest.java
  src/main/java/com/ssafy/tourmates/client/api/dto/hotplace/response/DetailHotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/client/api/dto/hotplace/response/HotPlaceResponse.java
  src/main/java/com/ssafy/tourmates/client/board/Board.java
  src/main/java/com/ssafy/tourmates/client/hashtag/Hashtag.java
  src/main/java/com/ssafy/tourmates/client/hashtag/HotPlaceHashtag.java
  src/main/java/com/ssafy/tourmates/client/hashtag/repository/HashtagQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/hashtag/repository/HashtagRepository.java
  src/main/java/com/ssafy/tourmates/client/hashtag/service/HashtagService.java
  src/main/java/com/ssafy/tourmates/client/hashtag/service/impl/HashtagServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/HotPlace.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/HotPlaceQueryRepository.java
  src/main/java/com/ssafy/tourmates/client/hotplace/repository/dto/HotPlaceSearchCondition.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/dto/AddHotPlaceDto.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceQueryServiceImpl.java
  src/main/java/com/ssafy/tourmates/client/hotplace/service/impl/HotPlaceServiceImpl.java
Labels: feature
